version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - localnet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: edgar.scott8908@gmail.com
      PGADMIN_DEFAULT_PASSWORD: escott
    ports:
      - "8080:80"
    networks:
      - localnet

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.jupyterlab
    image: custom-jupyterlab:latest
    container_name: jupyterlab
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - /home/escott/data_analysis:/home/jovyan
    command: start-notebook.sh --NotebookApp.token=''      
    networks:
      - localnet

volumes:
  pgdata:

networks:
  localnet:

