version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - localnet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: edgar.scott8908@gmail.com
      PGADMIN_DEFAULT_PASSWORD: escott
    ports:
      - "8080:80"
    networks:
      - localnet

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.jupyterlab
    image: custom-jupyterlab:latest
    container_name: jupyterlab
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - /home/escott/data_analysis:/home/jovyan
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: start-notebook.sh --NotebookApp.token=''      
    networks:
      - localnet

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1  # Or your preferred version
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - /home/escott/data_analysis/mlflow:/mlflow/mlruns  # Local volume for experiment logs
    environment:
      - MLFLOW_BACKEND_STORE_URI=/mlflow/mlruns
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns
    networks:
      - localnet

volumes:
  pgdata:

networks:
  localnet:
    
